//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geometrix_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_Produccion
    {
        public int ID_IT_Produccion { get; set; }
        public int ID_Produccion { get; set; }
        public int ID_Figura { get; set; }
        public int Cantidad { get; set; }
        public decimal Total_Costo { get; set; }
    
        public virtual Figuras Figuras { get; set; }
        public virtual Produccion Produccion { get; set; }
    }
}
