//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geometrix_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsensusEntities : DbContext
    {
        public ConsensusEntities()
            : base("name=ConsensusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Figuras> Figuras { get; set; }
        public virtual DbSet<IT_Produccion> IT_Produccion { get; set; }
        public virtual DbSet<Produccion> Produccion { get; set; }
        public virtual DbSet<Sets> Sets { get; set; }
        public virtual DbSet<Sets_Figuras> Sets_Figuras { get; set; }
    }
}
