//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geometrix_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produccion()
        {
            this.IT_Produccion = new HashSet<IT_Produccion>();
        }
    
        public int ID_Produccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Precio_Total { get; set; }
        public decimal Total_Costo { get; set; }
        public decimal Ganancia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_Produccion> IT_Produccion { get; set; }
    }
}
