//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geometrix_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sets_Figuras
    {
        public int ID_Figura { get; set; }
        public int ID_Set { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio_Set { get; set; }
    }
}
